# Generated by Django 4.2.1 on 2023-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='find',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
