# Generated by Django 4.2.1 on 2023-07-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_travelplan_generated_itinerary_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelplan',
            old_name='no_of_adults',
            new_name='no_of_visitors',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='no_of_children',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='no_of_events',
        ),
    ]
