# Generated by Django 4.2.1 on 2023-07-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_rename_no_of_adults_travelplan_no_of_visitors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelplan',
            old_name='no_of_visitors',
            new_name='no_of_adults',
        ),
    ]
